hmcts/spring-boot-template

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/demo/Application.java
I upgraded claimstore checkstyle to remove the hack that we used to fail on
warnings as there is now a property for it, also updated rules to
closely match what we have in the claimstore, happy to undo them if you
don't see any value.
Rules such as no unused imports and hide utility class constructors have
been added.
> Upgrade checkstyle

- build.gradle
Spring Boot enforces it's own version of logback which is 1.1.11. Need to specifically state in the list of dependencies both classic and core libraries to be 1.2.3 - the latest. It is recommended for all spring boot projects which uses logstash incorporated in java-logging library
```
[ ] Yes
[x] No
```
> Specify correct logback version to be used

- build.gradle
As per [documentation](https://github.com/hmcts/java-logging/tree/master/java-logging-appinsights#product-version) in `java-logging-appinsights` module in order to populate project version in Azure portal we need to set MANIFEST.MF with `Implementation-Version`.
- Takes no affect if you don't use appinsights
- Can be used for other purposes at your will
```
[ ] Yes
[x] No
```
> Include implementation-version for installed jars

- build.gradle
Will no longer report on untested private constructors in utility classes.
> Upgrade jacoco

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RPE-371
- Changes replicated from hmcts/job-scheduler#76
- Spring boot doesn't honour db settings without tomcat prefix.
```
[ ] Yes
[x ] No
```
> Add db connection settings in template to be used across all java projects

- src/main/resources/application.yaml
IntelliJ complained it didn't exist, I looked it up and it doesn't, I assume test-while-idle was intended and that's already in there
https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html#Common_Attributes
> Remove nonexistent property

- build.gradle
Missed dependency fix for guava. Incompatible among older versions getting selected by spring dependency manager causes checkstyle fail.
```
[ ] Yes
[x] No
```
> [HOTFIX] Fix correct guava version

- bin/init.sh
Before:
```
$ ./bin/init.sh port package [slug]
```
Now:
```
$ ./bin/init.sh
Port number for new app: 1234
Replace `demo` package name with: omed
Repo slug: (leave blank for "spring-boot-template") some-slug
```
```
[ ] Yes
[x] No
```
> Make script init more human friendly

- .travis.yml
- README.md
- bin/init.sh
- build.gradle
Was missing few bits:
- correct path to root controller
- normal way of renaming the directory
- fix for absolute path of the script/project
Bonus:
- include `spring-boot-starter-json` introduced since spring boot 2
- build only against master to reduce travis resources and github api hit rota
```
[ ] Yes
[x] No
```
> Fix init script

- build.gradle
Notes:
- spring boot 2.0.2 solves a bunch of bugfixes
- having cloud in RC1 instead of M9 is better. right?
```
[ ] Yes
[x] No
```
> Update spring boot versions

- README.md
- build.gradle
- src/main/java/uk/gov/hmcts/reform/demo/Application.java
Removing hystrix dashboard as it is not used anyway. Hystrix circuit breaker is highly recommended to be used in any service - it is up to the project developers to integrate/disregard it
```
[ ] Yes
[x] No
```
> Remove hystrix dashboard dependency

- infrastructure/main.tf
Its defined in module web app, having it in main.tf means tagging doesn't get applied
> Remove resource group definition

- bin/init.sh
Since `sed` is incompatible between different OS and one command line is used with `perl`, all commands are replaced with `perl`. Addressing #58 altogether.
Note to reviewer: please test if possible
Another note: `mv` has been replaced to `git mv` for better git history. And it is git versioning anyway so best to use appropriate tools for this action
```
[ ] Yes
[x] No
```
> Update init script

- bin/init.sh
PR to fix issue #74 
Replaces cd with pushd/popd and removes the call to realpath as it's not necessary. Any successful invocation of the script from an interactive terminal (which it needs anyway) should have a perfectly valid path that can be given to pushd/popd
> Replace use of cd and realpath with pushd/popd

- infrastructure/main.tf
resource_group_name should be automatically built by the default value
down the app module. 
https://github.com/hmcts/cnp-module-webapp/blob/master/main.tf#L3
don't need to have it. it is already build into the module.
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x] No
```
> terraform can't fetch a resource definition that is not here yet.

- .editorconfig
Prevent things like:
```
longServiceName.longMethodName(longParamXX,
longParamYY, longParamZZ);
```
and default to this instead:
```
longServiceName.longMethodName(
longParamXX,
longParamYY,
longParamZZ
);
```
See: https://github.com/hmcts/bulk-scan-processor/pull/732
```
[ ] Yes
[ ] No
```
> Add additional intellij editorconfig features

- build.gradle
This logs a message on every request with how long it took, it's annoying log spam in most cases, and app insights does this for us
> Remove java-logging-spring

- build.gradle
This lib is needed to configure Java apps with env vars in AKS envs.  Should be in the template.
> Adding missing lib for starter

- build.gradle
Downgrade spring boot as the version used previously 2.3.2.RELEASE has an issue
with serving the readiness and liveness endpoints.
> Downgrade spring boot

- charts/rpe-spring-boot-template/values.preview.template.yaml
Remove empty environment section as this will overwrite any environment variables set in values.yaml which means
they are not set for PR builds. This can be really confusing if you are setting them and then they do not appear
on your PR builds. Probably better to have this so you have to add it in rather than there by default.
> Fix empty environment variables

- build.gradle
- Use mavenCentral repo before trying jcenter
> DTSPO-1875 - use mavencentral repo before jcenter

- .github/workflows/ci.yml
N/A
Updated the versions of the GitHub actions used in CI workflow.  This resolves warnings about the use of deprecated features when the workflow is executed.
For reference the warnings were:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
[ ] Yes
[x] No
```
> Updated GitHub actions versions in CI workflow

- .github/workflows/publish-openapi.yaml
- README.md
- src/integrationTest/java/uk/gov/hmcts/reform/demo/openapi/OpenAPIPublisherTest.java
- src/main/resources/application.yaml
see 
- https://github.com/hmcts/workflow-publish-openapi-spec/pull/1
- https://github.com/hmcts/.github/pull/12
People no longer need to set this up themselves separately and we only have one central workflow for the simple case, people can customise it if they need to
> DTSPO-13135 Add OpenAPI publishing by default

- .github/renovate.json
see https://docs.renovatebot.com/config-presets/#organization-level-presets
and
https://github.com/hmcts/.github/pull/19
Used local to be consistent with the onboarding PR:
https://github.com/hmcts/nodejs-info-provider/pull/41
> Use organisation preset for renovate

- .github/workflows/ci.yml
Needs an API key otherwise it's too slow, this is done by Jenkins anyway
> Remove dependency check

- Dockerfile
- lib/applicationinsights.json
Incorporates https://github.com/hmcts/spring-boot-template/pull/570
Adapting to https://github.com/microsoft/ApplicationInsights-Java/pull/3463
> Upgrade appinsights agent to 3.5.2
