README.md, build.gradle, src/main/java/uk/gov/hmcts/reform/demo/Application.java
https://tools.hmcts.net/jira/browse/RPE-31
Add Hystrix to the project:
- add Hystrix libraries
- enable circuit breaker for the application
Also, add licence information to the readme.
```
[ ] Yes
[x] No
```
=> Add Hystrix to the project

README.md, build.gradle
Remove SonarQube from the project.
It's not decided if we're going to use it.
```
[ ] Yes
[x] No
```
=> RPE-31: remove SonarQube

src/main/resources/application.yaml
=> Dont disable security for management endpoints

README.md
Make minor styling fixes in the readme
```
[ ] Yes
[x] No
```
=> RPE-31: make minor styling fixes in the readme

.gitignore
Created by IntelliJ 2017.2
```
[ ] Yes
[x] No
```
=> Add out/ directory to .gitignore

build.gradle, config/checkstyle/checkstyle.xml
Update dependencies:
- latest logging version
- latest checkstyle
```
[ ] Yes
[x] No
```
=> Dependency update

README.md, bin/run-in-docker.sh, docker-compose.yml
Introducing common script for running spring boot service in docker
```
[ ] Yes
[x] No
```
=> Introduce run-in-docker shell script

build.gradle, web.config
Add web.config. Also (related), specify the name of the output jar.
```
[ ] Yes
[x] No
```
=> Add web.config

Dockerfile, LICENSE, README.md, bin/init.sh, build.gradle, docker-compose.yml, src/main/java/uk/gov/hmcts/reform/demo/Application.java, src/main/resources/application.yaml
To save the grunt work of setting up project from this skeleton a script is introduced in this PR.
Bonus points:
- Removes all TODOs ~except one - the title of the project in README~
- Updates year in LICENCE
- Fixes typos in README
```
[ ] Yes
[x] No
```
=> Feature: initialise project

bin/init.sh, src/main/java/uk/gov/hmcts/reform/demo/controllers/HelloWorldEndpoint.java, src/main/java/uk/gov/hmcts/reform/demo/controllers/RootController.java, src/test/java/uk/gov/hmcts/reform/demo/controllers/GetWelcomeTest.java, src/test/java/uk/gov/hmcts/reform/demo/controllers/HelloWorldTest.java
Contr-PR for Azure service feature "Always On" hitting the root endpoint. Creating a hello world controller to respond with welcome message and get rid of faulty 404s in order to avoid misguiding reports
```
[ ] Yes
[x] No
```
=> Introduce root endpoint

build.gradle, config/pmd/ruleset.xml, src/main/java/uk/gov/hmcts/reform/demo/Application.java, src/test/java/uk/gov/hmcts/reform/demo/controllers/GetWelcomeTest.java
Long awaited update. Using categories
```
[ ] Yes
[x] No
```
=> Upgrade PMD to 6.3.0

bin/init.sh, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/prod.tfvars, infrastructure/state.tf, infrastructure/variables.tf
Adding core setup of infrastructure to set base of empty deployment once pipeline script is in place
```
[ ] Yes
[x] No
```
=> Add core infrastructure code

config/pmd/ruleset.xml
Updating rules to match the ones already revisited in `java-logging` library and strongly based on them
```
[ ] Yes
[x] No
```
=> Update default ruleset to fit HMCTS rules

infrastructure/main.tf, infrastructure/variables.tf
Add `common_tags` input variable to terraform code
```
[ ] Yes
[x] No
```
=> Add common_tags input variable to terraform code

src/main/java/uk/gov/hmcts/reform/demo/controllers/RootController.java
Before the app was returning 204 on all unknown endpoints and not just /,
It was preventing 404s from being returned for unknown endpoints, confusing behaviour.
```
[ ] Yes
[ ] No
```
=> Fix root controller mapping

infrastructure/main.tf
tf doesn't support basic type such as boolean
```
[ ] Yes
[x] No
```
=> Fix usage of boolean in terraform code

Dockerfile, docker-compose.yml
Align structure with latest usage compared to other projects.
#65 
```
[ ] Yes
[x] No
```
=> Update docker compose and Dockerfile

build.gradle
adding the liveness health module.
=> adding the liveness endpoint for the new charts 

config/owasp/suppressions.xml
Suppressing CVE as its a false positive
```
[ ] Yes
[x] No
```
=> Suppressing false positive

build.gradle
Fixing dependency  check
NA
Fixing dependency  check
```
[ ] Yes
[x] No
```
=> Fixing dep check

.gitignore
- [ x ] commit messages are meaningful and follow good commit message guidelines
I am not sure if that is a typo issue or mac version issue.
However, the standard **ds_store** is with an uppercase on the S
We might need to have both of them.
```
[ ] Yes
[x ] No
```
=> fix ignore file

build.gradle
add suppression for CVE-2018-1258 due to false positive
add suppression for CVE-2018-1258 due to false positive
```
[ ] Yes
[x ] No
```
=> bump spring version (#84)

build.gradle, config/owasp/suppressions.xml
add suppression due to false positive
add suppression due to false positive
```
[ ] Yes
[x ] No
```
=> Bump spring version

config/owasp/suppressions.xml
suppress false positive
suppress false positive
```
[ ] Yes
[x ] No
```
=> suppressed spring_security

charts/rpe-spring-boot-template/Chart.yaml, charts/rpe-spring-boot-template/requirements.yaml, charts/rpe-spring-boot-template/values.aat.template.yaml, charts/rpe-spring-boot-template/values.preview.template.yaml, charts/rpe-spring-boot-template/values.yaml
https://tools.hmcts.net/jira/browse/RPE-914
RPE 914
```
[ ] Yes
[x] No
```
=> Migrating to latest java chart and refactoring preview configs

build.gradle, infrastructure/main.tf
Nothing major, just updating the old link to the new one.
And removed a duplicated dependency
```
[ ] Yes
[x ] No
```
=> use the correct link to fetch the module

build.gradle, config/owasp/suppressions.xml
Fixing owasp dependency check issues
```
[ ] Yes
[x] No
```
=> Fixing owasp dependency check issues

.dependabot/config.yml, build.gradle, config/owasp/suppressions.xml, config/pmd/ruleset.xml, gradle/wrapper/gradle-wrapper.properties
Upgrade all versions, fix PMD deprecation warnings, enable dependabot
```
[ ] Yes
[ ] No
```
=> Upgrade versions

build.gradle
=> updgrade jackson databind

config/owasp/suppressions.xml
=> fix dependency check

build.gradle, config/checkstyle/checkstyle.xml
=> fixing owasp issue, bumping checkstyle

Dockerfile, charts/rpe-spring-boot-template/Chart.yaml, charts/rpe-spring-boot-template/requirements.yaml, charts/rpe-spring-boot-template/values.yaml
=> Moving to latest base image, chart

Dockerfile, build.gradle
=> Bumping AI agent

config/owasp/suppressions.xml
=> Suppress cve false positive

config/owasp/suppressions.xml
Suppressing only for Jan.
```
[ ] Yes
[x] No
```
=> Suppress owasp issues

build.gradle
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Use Jacoco XML report for SonarCloud

charts/rpe-spring-boot-template/requirements.yaml
=> Bump java chart

charts/rpe-spring-boot-template/values.yaml
=> add identity name

bin/init.sh, src/integrationTest/java/uk/gov/hmcts/reform/demo/config/SwaggerPublisher.java, src/integrationTest/java/uk/gov/hmcts/reform/demo/config/SwaggerPublisherTest.java, src/test/java/uk/gov/hmcts/reform/rsecheck/DemoUnitTest.java
NA
Small change about generation of new project
Adding a default unit test
Fixing default integration test
```
[ ] Yes
[ x] No
```
=> Fix Project generation

README.md, bin/init.sh
NA
When a project is generated the port number is also updated in the helm charts
```
[ ] Yes
[x ] No
```
=> replace chart application port

build.gradle, config/owasp/suppressions.xml
=> Upgrade dependencies

bin/init.sh, charts/rpe-spring-boot-template/Chart.yaml
Update init file to generate helm charts matching the details of the generated project
```
[ ] Yes
[ x] No
```
=> Generate helm charts

Jenkinsfile_template, bin/init.sh
Add a new CNP file when a project is generated
```
[ ] Yes
[ x] No
```
=> Generate CNP file

config/owasp/suppressions.xml
update eve suppression for false positive crypto lib 
```
[ ] Yes
[ x] No
```
=> update crypto suppression

.github/renovate.json, charts/rpe-spring-boot-template/Chart.yaml, charts/rpe-spring-boot-template/requirements.yaml
=> Adding renovate for helm-requirements and helm apiversion v2

bin/init.sh, build.gradle, charts/rpe-spring-boot-template/values.yaml, src/main/resources/application.yaml
Update spring boot to version 2.4, remove the hmcts properties volume, update configuration to include app insights config.
=> Upgrade to spring boot 2.4

charts/rpe-spring-boot-template/values.yaml
=> Adding alias to secret

README.md, build.gradle, src/main/java/uk/gov/hmcts/reform/demo/Application.java
Fixes https://github.com/hmcts/spring-boot-template/issues/314
Removed Hysterix and Tomcat to enable the application to work
```
[ ] Yes
[ X ] No
```
=> Removed hysterix and tomcat

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/demo/smoketests/SmokeTestConfiguration.java, src/smokeTest/java/uk/gov/hmcts/reform/pip/rules/smoketests/SmokeTestConfiguration.java, src/smokeTest/resources/application.properties
Add generic smoke tests so the pipeline will pass.
```
[ ] Yes
[ X ] No
```
=> Add generic smoke tests

Dockerfile, build.gradle
https://tools.hmcts.net/browse/DTSPO-6152
Use Java 17
```
[ ] Yes
[x] No
```
=> DTSPO-6152 - upgrade to Java 17

.github/renovate.json, Dockerfile, build.gradle, config/owasp/suppressions.xml
Also adds Renovate config to upgrade agent.
```
[ ] Yes
[x] No
```
=> Upgrade Spring boot with Appinsights agent

config/owasp/suppressions.xml
=> Remove unwanted suppressions

.github/workflows/codeql.yml
I tested in a fork already and there was no issues
=> Enable CodeQL code scanning by default

.github/renovate.json
Use renovate global presets
```
[ ] Yes
[x] No
```
=> DTSPO-11734 - renovate - use global presets

.github/CODEOWNERS
add [SDS Community Maintained Software](https://github.com/orgs/hmcts/teams/sds-community-maintained-software) group to codeowners
```
[ ] Yes
[x] No
```
=> add sds-community-maintained-software to CODEOWNERS file

build.gradle, src/main/resources/application.yaml
[DTSPO-15623](https://tools.hmcts.net/jira/browse/DTSPO-15623)
Adding database to readiness probes,  was tested on this pr https://github.com/hmcts/cnp-plum-recipes-service/pull/885 using this url https://plum-recipe-backend-pr-885.preview.platform.hmcts.net/health/db
=> DTSPO-15623 Update readiness probes in spring-boot-template

src/main/resources/application.yaml
[DTSPO-15623](https://tools.hmcts.net/jira/browse/DTSPO-15623)
updating health check group from db to liveness
```
[ ] Yes
[x] No
```
=> DTSPO-15623 updating health check group

src/main/resources/application.yaml
[DTSPO-14035](https://tools.hmcts.net/jira/browse/DTSPO-14035)
Updating db check to use readiness probe instead of liveness
```
[ ] Yes
[x] No
```
=> DTSPO-14035 Updating health-probe-template

src/main/resources/application.yaml
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/DTSPO-15306
* add graceful shutdown
```
[ ] Yes
[x] No
```
=> DTSPO-15306: add shutdown: graceful

README.md, bin/run-in-docker.sh
https://tools.hmcts.net/jira/browse/DTSPO-18098
Updated README about new Docker Compose command
```
[ ] Yes
[x] No
```
=> updated README about new Docker Compose command

build.gradle
Add azure artifacts
```
[ ] Yes
[x] No
```
=> Add azure artifacts
